apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

  images:
- name: mattermost/mattermost-enterprise-edition
  newName: mattermost/mattermost-enterprise-edition
  newTag: 5.27.0