apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

images:
- name: mattermost/mattermost-enterprise-edition
  newName: cnbb-docker-local.bin.swisscom.com/swisscom/mattermost-enterprise-edition
  newTag: 5.27.0